on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say service count
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: "./"

    # - name: Install Dependencies
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 16
    # - run: npm i -g yarn
    # - run: yarn install
    # - run: ls

    - name: Deploy SST app
      id: deploy
      uses: quenginedev/sst-deploy@main
      with:
        access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_DEFAULT_REGION }}
        path: './'